---
title       : Informe diciembre 2016
subtitle    : Para ALSA
author      : Bayes Forecast. Madrid. 27 de diciembre de 2016.
job         : 
logo        : logobayes2.png 
biglogo     : ALSA_logo.svg.png
framework   : io2012 #{io2012,html5slides,shower,dzslides, ...}
highlighter : highlight.js  #{highlight.js,prettify, highlight}
hitheme     : tomorrow # 
widgets     : [shiny, interactive, mathjax]  #{mathjax, quiz, bootstrap}
mode        : selfcontained # {standalone,selfcontained,draft}
ext_widgets : {rCharts: [libraries/nvd3,libraries/morris,libraries/highcharts]}
knit        : slidify::knit2slides

--- &slide2 .segue bg:#0C2F59

## Descomposición de efectos


--- #dillinger #id bg:#FFFFFF

## Descomposición de efectos
# Diciembre 2014 - Noviembre 2016
# Asturias


<iframe src = 'charts/DecoAst_e20161221.01.html'></iframe>


--- #dillinger #id bg:#FFFFFF

## Descomposición de efectos
# Diciembre 2014 - Noviembre 2016
# Barcelona


<iframe src = 'charts/DecoBar_e20161221.01.html'></iframe>


--- #dillinger #id bg:#FFFFFF

## Descomposición de efectos
# Diciembre 2014 - Noviembre 2016
# Bilbao


<iframe src = 'charts/DecoBil_e20161221.01.html'></iframe>


--- #dillinger #id bg:#FFFFFF

## Descomposición de efectos
# Diciembre 2014 - Noviembre 2016
# Alicante


<iframe src = 'charts/DecoAli_e20161221.01.html'></iframe>


--- #dillinger #id bg:#FFFFFF

## Descomposición de efectos
# Diciembre 2014 - Noviembre 2016
# Granada


<iframe src = 'charts/DecoGra_e20161221.01.html'></iframe>


--- #dillinger #id bg:#FFFFFF

## Descomposición de efectos
# Diciembre 2014 - Noviembre 2016
# Galicia


<iframe src = 'charts/DecoGal_e20161221.01.html'></iframe>







--- &slide2 .segue bg:#0C2F59

## Análisis de las Fuentes de Variación


--- #dillinger #id bg:#FFFFFF

## Due-To
# Diciembre 2015 - Noviembre 2016
# Asturias


<iframe src = 'charts/DuetoAst_e20161221.01.html'></iframe>





--- #dillinger #id bg:#FFFFFF

## Due-To
# Diciembre 2015 - Noviembre 2016
# Barcelona


<iframe src = 'charts/DuetoBar_e20161221.01.html'></iframe>





--- #dillinger #id bg:#FFFFFF

## Due-To
# Diciembre 2015 - Noviembre 2016
# Bilbao


<iframe src = 'charts/DuetoBil_e20161221.01.html'></iframe>





--- #dillinger #id bg:#FFFFFF

## Due-To
# Diciembre 2015 - Noviembre 2016
# Alicante


<iframe src = 'charts/DuetoAli_e20161221.01.html'></iframe>





--- #dillinger #id bg:#FFFFFF

## Due-To
# Diciembre 2015 - Noviembre 2016
# Granada


<iframe src = 'charts/DuetoGra_e20161221.01.html'></iframe>





--- #dillinger #id bg:#FFFFFF

## Due-To
# Diciembre 2015 - Noviembre 2016
# Galicia


<iframe src = 'charts/DuetoGal_e20161221.01.html'></iframe>






--- &slide2 .segue bg:#0C2F59

## Gracias